'use client';
import { useEffect, useState } from 'react';
import { BarChart2, Leaf, Recycle, Droplets, Download, Loader2 } from 'lucide-react';
import { BarChart, Bar, XAxis, YAxis, Tooltip, ResponsiveContainer, CartesianGrid, RadarChart, Radar, PolarGrid, PolarAngleAxis } from 'recharts';
import TopBar from '../../components/TopBar';
import StatCard from '../../components/StatCard';
import { jsPDF } from 'jspdf';

const sdgData = [
  { sdg: 'SDG 6',  score: 82 },
  { sdg: 'SDG 11', score: 74 },
  { sdg: 'SDG 12', score: 91 },
  { sdg: 'SDG 13', score: 78 },
  { sdg: 'SDG 17', score: 65 },
];

// ── PDF: Monthly Impact Report ───────────────────────────────────────────────
function downloadImpactPDF(monthly: any[], totals: any) {
  const pdf = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const W = 210;
  const generated = new Date().toLocaleDateString('en-IN', { day: 'numeric', month: 'long', year: 'numeric' });

  pdf.setFillColor(27, 94, 32); pdf.rect(0, 0, W, 55, 'F');
  pdf.setFillColor(245, 158, 11); pdf.rect(0, 55, W, 2.5, 'F');

  pdf.setTextColor(255,255,255); pdf.setFontSize(20); pdf.setFont('helvetica','bold');
  pdf.text('ReLoop', W/2, 18, { align: 'center' });
  pdf.setFontSize(8); pdf.setFont('helvetica','normal'); pdf.setTextColor(180,220,180);
  pdf.text('CIRCULAR RESOURCE MANAGEMENT PLATFORM', W/2, 25, { align: 'center' });
  pdf.setFontSize(15); pdf.setFont('helvetica','bold'); pdf.setTextColor(255,255,255);
  pdf.text('Monthly Impact Report — 2026', W/2, 40, { align: 'center' });
  pdf.setFontSize(8); pdf.setFont('helvetica','normal'); pdf.setTextColor(200,230,200);
  pdf.text('Symbiosis University of Applied Sciences, Indore', W/2, 48, { align: 'center' });

  // Summary boxes
  const summaries = [
    ['CO2 Saved (YTD)',     `${Number(totals.total_co2||0).toFixed(1)} T`],
    ['Water Conserved',    `${(Number(totals.total_water||0)/1000).toFixed(1)} KL`],
    ['Total Revenue (YTD)',`₹${Number(totals.total_revenue||0).toLocaleString('en-IN')}`],
    ['Items Diverted',     `${Number(totals.total_items||0).toFixed(0)}`],
  ];
  const bW = 40, bX = 15, bY = 65;
  summaries.forEach(([label, val], i) => {
    const x = bX + i * (bW + 5);
    pdf.setFillColor(241, 248, 240); pdf.roundedRect(x, bY, bW, 20, 2, 2, 'F');
    pdf.setFontSize(7); pdf.setFont('helvetica','bold'); pdf.setTextColor(156,163,175);
    pdf.text(label.toUpperCase(), x+3, bY+6);
    pdf.setFontSize(11); pdf.setFont('helvetica','bold'); pdf.setTextColor(27,94,32);
    pdf.text(val, x+3, bY+15);
  });

  // Monthly table
  pdf.setFontSize(11); pdf.setFont('helvetica','bold'); pdf.setTextColor(31,42,36);
  pdf.text('Monthly Breakdown', 20, 100);
  pdf.setFillColor(27,94,32); pdf.rect(20, 103, 170, 8, 'F');
  ['Month','CO2 (T)','Water (KL)','Revenue (₹)','Oil (L)','E-Waste Items'].forEach((h, i) => {
    pdf.setFontSize(7); pdf.setFont('helvetica','bold'); pdf.setTextColor(255,255,255);
    pdf.text(h, 22 + i*28, 108);
  });

  monthly.forEach((m: any, i: number) => {
    const y = 114 + i * 8;
    if (i % 2 === 0) { pdf.setFillColor(245,247,245); pdf.rect(20, y-4, 170, 8, 'F'); }
    const row = [
      m.month,
      Number(m.co2_saved||0).toFixed(2),
      (Number(m.water_saved||0)/1000).toFixed(1),
      `${Number(m.revenue||0).toLocaleString('en-IN')}`,
      Number(m.oil_collected||0).toFixed(0),
      String(m.ewaste_items||0),
    ];
    row.forEach((val, j) => {
      pdf.setFontSize(8); pdf.setFont('helvetica','normal'); pdf.setTextColor(31,42,36);
      pdf.text(String(val), 22 + j*28, y+1);
    });
  });

  const footY = 114 + monthly.length * 8 + 10;
  pdf.setDrawColor(229,231,235); pdf.setLineWidth(0.5); pdf.line(20, footY, W-20, footY);
  pdf.setFontSize(7); pdf.setTextColor(156,163,175);
  pdf.text(`Generated by ReLoop on ${generated} · Team EcoNova · Green Tech Hackathon 2026`, W/2, footY+6, { align: 'center' });

  pdf.save('ReLoop-Monthly-Impact-Report.pdf');
}

// ── PDF: CSR/ESG Report ──────────────────────────────────────────────────────
function downloadESGPDF(totals: any) {
  const pdf = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const W = 210;
  const generated = new Date().toLocaleDateString('en-IN', { day: 'numeric', month: 'long', year: 'numeric' });

  pdf.setFillColor(33, 150, 243); pdf.rect(0, 0, W, 55, 'F');
  pdf.setFillColor(245, 158, 11); pdf.rect(0, 55, W, 2.5, 'F');

  pdf.setTextColor(255,255,255); pdf.setFontSize(20); pdf.setFont('helvetica','bold');
  pdf.text('ReLoop', W/2, 18, { align: 'center' });
  pdf.setFontSize(8); pdf.setFont('helvetica','normal'); pdf.setTextColor(180,210,255);
  pdf.text('CIRCULAR RESOURCE MANAGEMENT PLATFORM', W/2, 25, { align: 'center' });
  pdf.setFontSize(15); pdf.setFont('helvetica','bold'); pdf.setTextColor(255,255,255);
  pdf.text('CSR / ESG Report — Q2 2026', W/2, 40, { align: 'center' });
  pdf.setFontSize(8); pdf.setFont('helvetica','normal'); pdf.setTextColor(200,225,255);
  pdf.text('Symbiosis University of Applied Sciences, Indore', W/2, 48, { align: 'center' });

  // SDG scores
  pdf.setFontSize(12); pdf.setFont('helvetica','bold'); pdf.setTextColor(31,42,36);
  pdf.text('SDG Alignment Scores', 20, 72);

  sdgData.forEach((s, i) => {
    const y = 80 + i * 14;
    pdf.setFillColor(241,248,240); pdf.roundedRect(20, y, 170, 11, 2, 2, 'F');
    pdf.setFontSize(9); pdf.setFont('helvetica','bold'); pdf.setTextColor(31,42,36);
    pdf.text(s.sdg, 25, y+7);
    // Progress bar
    const barW = 100, barX = 55;
    pdf.setFillColor(229,231,235); pdf.roundedRect(barX, y+3, barW, 5, 1, 1, 'F');
    const fillW = (s.score / 100) * barW;
    pdf.setFillColor(27,94,32); pdf.roundedRect(barX, y+3, fillW, 5, 1, 1, 'F');
    pdf.setFontSize(8); pdf.setFont('helvetica','bold'); pdf.setTextColor(27,94,32);
    pdf.text(`${s.score}%`, barX + barW + 4, y+7);
  });

  const impactY = 80 + sdgData.length * 14 + 15;
  pdf.setFontSize(12); pdf.setFont('helvetica','bold'); pdf.setTextColor(31,42,36);
  pdf.text('Environmental Impact Summary', 20, impactY);

  const impacts = [
    ['Carbon Footprint Reduced',  `${Number(totals.total_co2||0).toFixed(1)} tonnes CO2e`],
    ['Municipal Water Offset',    `${(Number(totals.total_water||0)/1000).toFixed(1)} KL`],
    ['Circular Economy Revenue',  `₹${Number(totals.total_revenue||0).toLocaleString('en-IN')}`],
    ['Waste Diverted from Landfill', `${Number(totals.total_items||0).toFixed(0)} items + oil`],
  ];
  impacts.forEach(([label, val], i) => {
    const y = impactY + 8 + i * 12;
    pdf.setFillColor(232,242,252); pdf.roundedRect(20, y, 170, 10, 2, 2, 'F');
    pdf.setFontSize(8); pdf.setFont('helvetica','normal'); pdf.setTextColor(91,107,99);
    pdf.text(label, 25, y+6.5);
    pdf.setFont('helvetica','bold'); pdf.setTextColor(33,150,243);
    pdf.text(String(val), W-25, y+6.5, { align: 'right' });
  });

  pdf.setFontSize(7); pdf.setTextColor(156,163,175);
  pdf.text(`Generated by ReLoop on ${generated} · Team EcoNova · Green Tech Hackathon 2026`, W/2, 285, { align: 'center' });

  pdf.save('ReLoop-CSR-ESG-Report-Q2.pdf');
}

// ── CSV: Transaction Ledger ──────────────────────────────────────────────────
function downloadLedgerCSV(monthly: any[]) {
  const header = ['Month','Oil Collected (L)','E-Waste Items','Revenue (INR)','CO2 Saved (T)','Water Saved (L)'];
  const rows = monthly.map((m: any) => [
    m.month,
    Number(m.oil_collected||0).toFixed(0),
    m.ewaste_items||0,
    Number(m.revenue||0).toFixed(0),
    Number(m.co2_saved||0).toFixed(2),
    Number(m.water_saved||0).toFixed(0),
  ]);
  const csv = [header, ...rows].map(r => r.map((c: any) => `"${c}"`).join(',')).join('\n');
  const blob = new Blob([csv], { type: 'text/csv' });
  const url  = URL.createObjectURL(blob);
  const a    = document.createElement('a');
  a.href = url; a.download = 'ReLoop-Transaction-Ledger.csv'; a.click();
  URL.revokeObjectURL(url);
}

// ── CSV: NAAC Green Campus ───────────────────────────────────────────────────
function downloadNAACCSV(totals: any) {
  const rows = [
    ['Indicator','Value','Unit','SDG Mapping'],
    ['Carbon Emissions Reduced', Number(totals.total_co2||0).toFixed(1), 'Tonnes CO2e', 'SDG 13'],
    ['Water Conserved',          (Number(totals.total_water||0)/1000).toFixed(1), 'KL', 'SDG 6'],
    ['Circular Economy Revenue', Number(totals.total_revenue||0).toFixed(0), 'INR', 'SDG 12'],
    ['E-Waste Diverted',         String(totals.total_items||0), 'Items', 'SDG 11'],
    ['Oil Diverted from Landfill', Number(totals.total_oil||0).toFixed(0), 'Litres', 'SDG 12'],
    ['Compliance Score',         '96', '%', 'SDG 17'],
    ['Institution',              'Symbiosis University of Applied Sciences, Indore', '', ''],
    ['Period',                   'Jan–Jun 2026', '', ''],
    ['Platform',                 'ReLoop by Team EcoNova', '', ''],
  ];
  const csv = rows.map(r => r.map((c: any) => `"${c}"`).join(',')).join('\n');
  const blob = new Blob([csv], { type: 'text/csv' });
  const url  = URL.createObjectURL(blob);
  const a    = document.createElement('a');
  a.href = url; a.download = 'ReLoop-NAAC-Green-Campus.csv'; a.click();
  URL.revokeObjectURL(url);
}

export default function ReportsPage() {
  const [data, setData]       = useState<any>(null);
  const [loading, setLoading] = useState(true);
  const [dlKey, setDlKey]     = useState<string | null>(null);

  useEffect(() => {
    fetch('/api/reports').then(r => r.json()).then(d => { setData(d); setLoading(false); });
  }, []);

  const monthly = data?.monthly || [];
  const totals  = data?.totals  || {};
  const depts   = data?.depts   || [];
  const maxRevenue = Math.max(...depts.map((d: any) => Number(d.oil) * 30 + Number(d.ewaste) * 5000), 1);

  const exports = [
    {
      key: 'impact', label: 'Monthly Impact Report', desc: 'Oil, E-Waste & Water summary', format: 'PDF',
      fn: () => downloadImpactPDF(monthly, totals),
    },
    {
      key: 'esg', label: 'CSR/ESG Report (Q2)', desc: 'SDG-mapped compliance export', format: 'PDF',
      fn: () => downloadESGPDF(totals),
    },
    {
      key: 'ledger', label: 'Transaction Ledger', desc: 'All pickups & revenues', format: 'CSV',
      fn: () => downloadLedgerCSV(monthly),
    },
    {
      key: 'naac', label: 'NAAC Green Campus Data', desc: 'Formatted for NAAC submission', format: 'CSV',
      fn: () => downloadNAACCSV(totals),
    },
  ];

  const handleExport = (key: string, fn: () => void) => {
    setDlKey(key);
    setTimeout(() => { fn(); setDlKey(null); }, 300);
  };

  return (
    <div>
      <TopBar title="Reports & Impact" date="June 2026" />

      <div className="flex gap-4 mb-6">
        <StatCard label="CO2 Saved (YTD)"       value={`${Number(totals.total_co2||0).toFixed(1)}`}                             unit="T"    change="+2.4T MoM"      changeType="up"   icon={Leaf}     color="green" />
        <StatCard label="Water Conserved (YTD)"  value={`${(Number(totals.total_water||0)/1000).toFixed(1)}`}                    unit="K L"  change="+9.2K MoM"      changeType="up"   icon={Droplets} color="blue"  />
        <StatCard label="Total Revenue (YTD)"    value={`₹${Number(totals.total_revenue||0).toLocaleString('en-IN')}`}            change="+22% vs target" changeType="up"   icon={BarChart2} color="amber" />
        <StatCard label="Items Diverted"         value={`${Number(totals.total_items||0).toFixed(0)}`}                           change="All time"       changeType="info" icon={Recycle}  color="green" />
      </div>

      <div className="flex gap-5 mb-6">
        <div className="flex-1 bg-white rounded-2xl shadow-sm border border-gray-100 p-5">
          <h3 className="font-bold text-base mb-4" style={{ color: '#1F2A24' }}>REVENUE — 2026</h3>
          {loading ? <div className="text-sm text-gray-400 text-center py-10">Loading...</div> : (
            <ResponsiveContainer width="100%" height={200}>
              <BarChart data={monthly} barCategoryGap="25%">
                <CartesianGrid strokeDasharray="3 3" stroke="#F0F0F0" vertical={false} />
                <XAxis dataKey="month" axisLine={false} tickLine={false} tick={{ fill: '#5B6B63', fontSize: 12 }} />
                <YAxis axisLine={false} tickLine={false} tick={{ fill: '#5B6B63', fontSize: 12 }} tickFormatter={(v: number) => `₹${v/1000}K`} />
                <Tooltip formatter={(v: number) => [`₹${Number(v).toLocaleString('en-IN')}`, 'Revenue']} contentStyle={{ borderRadius: 8, border: '1px solid #E5E7EB' }} />
                <Bar dataKey="revenue" fill="#1B5E20" radius={[6,6,0,0]} />
              </BarChart>
            </ResponsiveContainer>
          )}
        </div>

        <div className="w-72 bg-white rounded-2xl shadow-sm border border-gray-100 p-5">
          <h3 className="font-bold text-sm mb-4" style={{ color: '#1F2A24' }}>SDG ALIGNMENT SCORES</h3>
          <ResponsiveContainer width="100%" height={200}>
            <RadarChart data={sdgData}>
              <PolarGrid />
              <PolarAngleAxis dataKey="sdg" tick={{ fill: '#5B6B63', fontSize: 11 }} />
              <Radar dataKey="score" stroke="#1B5E20" fill="#1B5E20" fillOpacity={0.2} />
            </RadarChart>
          </ResponsiveContainer>
        </div>
      </div>

      <div className="flex gap-5">
        <div className="flex-1 bg-white rounded-2xl shadow-sm border border-gray-100 p-5">
          <h3 className="font-bold text-base mb-4" style={{ color: '#1F2A24' }}>TOP DIVERTING DEPARTMENTS</h3>
          {loading ? <div className="text-sm text-gray-400 text-center py-6">Loading...</div> : (
            <div className="space-y-4">
              {depts.map((d: any, i: number) => {
                const total = Number(d.oil) * 30 + Number(d.ewaste) * 5000;
                const pct   = Math.round((total / maxRevenue) * 100);
                return (
                  <div key={i}>
                    <div className="flex items-center justify-between mb-1">
                      <span className="text-sm font-medium" style={{ color: '#1F2A24' }}>{d.department || 'Unknown'}</span>
                      <span className="text-xs" style={{ color: '#5B6B63' }}>{Number(d.oil).toFixed(0)}L oil · {d.ewaste} items</span>
                    </div>
                    <div className="w-full h-2 rounded-full bg-gray-100">
                      <div className="h-full rounded-full transition-all" style={{ width: `${pct}%`, background: '#1B5E20' }} />
                    </div>
                  </div>
                );
              })}
            </div>
          )}
        </div>

        <div className="w-72 bg-white rounded-2xl shadow-sm border border-gray-100 p-5">
          <h3 className="font-bold text-sm mb-4" style={{ color: '#1F2A24' }}>EXPORT REPORTS</h3>
          <div className="space-y-3">
            {exports.map(({ key, label, desc, format, fn }) => (
              <button key={key} onClick={() => handleExport(key, fn)}
                disabled={loading || dlKey === key}
                className="w-full flex items-center justify-between p-3.5 rounded-xl border border-gray-100 hover:bg-gray-50 text-left transition-colors disabled:opacity-60">
                <div>
                  <div className="text-sm font-semibold" style={{ color: '#1F2A24' }}>{label}</div>
                  <div className="text-xs" style={{ color: '#5B6B63' }}>{desc}</div>
                </div>
                <div className="flex items-center gap-1.5 text-xs font-semibold flex-shrink-0 ml-3" style={{ color: '#2196F3' }}>
                  {dlKey === key
                    ? <><Loader2 size={12} className="animate-spin" /> Wait...</>
                    : <><Download size={13} /> {format}</>}
                </div>
              </button>
            ))}
          </div>
        </div>
      </div>
    </div>
  );
}
